import "./tokens.css";
export { default as VgButton } from "./components/VgButton.vue";
export { default as VgBadge } from "./components/VgBadge.vue";
export { default as VgPanel } from "./components/VgPanel.vue";
export { default as VgField } from "./components/VgField.vue";
export { default as VgSwitch } from "./components/VgSwitch.vue";
export { default as VgTabs } from "./components/VgTabs.vue";
export { default as VgMeter } from "./components/VgMeter.vue";
export { default as VgStat } from "./components/VgStat.vue";
export { default as VgDialog } from "./components/VgDialog.vue";
