export const componentCatalog = [
  {
    name: "FzButton",
    props: "variant, size, loading, disabled, type",
    state: "native click",
    slots: "default, trailing",
    example: "",
  },
  {
    name: "FzField",
    props: "label, hint, error, type, placeholder, disabled",
    state: "v-model: string",
    slots: "leading, trailing",
    example: "",
  },
  {
    name: "FzSelect",
    props: "label, options, placeholder, disabled, name",
    state: "v-model: string",
    slots: "none",
    example: '<FzSelect v-model="role" label="Role" :options="roles" />',
  },
  {
    name: "FzCheckbox",
    props: "label, description, disabled, name",
    state: "v-model: boolean or indeterminate",
    slots: "none",
    example: "",
  },
  {
    name: "FzSlider",
    props: "label, min, max, step, unit, disabled, name",
    state: "v-model: number; commit(value)",
    slots: "none",
    example: "",
  },
  {
    name: "FzSwitch",
    props: "label, disabled",
    state: "v-model: boolean",
    slots: "none",
    example: "",
  },
  {
    name: "FzSegmented",
    props: "label, options",
    state: "v-model: string",
    slots: "none",
    example: "",
  },
  {
    name: "FzTabs",
    props: "label, options",
    state: "v-model: string",
    slots: "default",
    example: "",
  },
  {
    name: "FzStepper",
    props: "steps, label, linear",
    state: "v-model: number (1-based)",
    slots: "none",
    example: '<FzStepper v-model="step" label="Setup" :steps="steps" />',
  },
  {
    name: "FzPagination",
    props: "total, pageSize, label",
    state: "v-model: number (1-based)",
    slots: "none",
    example: "",
  },
  {
    name: "FzAccordion",
    props: "items, label, disabled",
    state: "v-model: string (single, collapsible)",
    slots: "title({item}), default({item})",
    example: '<FzAccordion v-model="expanded" label="Guide" :items="guide" />',
  },
  {
    name: "FzCarousel",
    props: "items with stable id, label",
    state: "v-model: number (0-based)",
    slots: "default({item,index})",
    example:
      '<FzCarousel v-model="slide" :items="builds" label="Builds">\n  <template #default="{item}">{{ item.name }}</template>\n</FzCarousel>',
  },
  {
    name: "FzDropdown",
    props: "label, items, heading, disabled",
    state: "v-model:open; select(value)",
    slots: "trigger",
    example: "",
  },
  {
    name: "FzDialog",
    props: "title, description, closeOnOutside, placement",
    state: "v-model: boolean",
    slots: "default({close}), footer({close})",
    example: "",
  },
  {
    name: "FzDrawer",
    props: "title, description, side, closeOnOutside",
    state: "v-model: boolean",
    slots: "default({close}), footer({close})",
    example: '<FzDrawer v-model="open" title="Filters">...</FzDrawer>',
  },
  {
    name: "FzPopover",
    props: "label",
    state: "v-model:open",
    slots: "trigger, default({close})",
    example: "",
  },
  {
    name: "FzTooltip",
    props: "text, delay",
    state: "hover/focus managed by primitive",
    slots: "default: one focusable trigger",
    example: "",
  },
  {
    name: "FzTable",
    props: "rows, columns, label",
    state: "v-model:sort; parent sorts rows",
    slots: "cell({row,column,value}), empty",
    example:
      '<FzTable v-model:sort="sort" :rows="rows" :columns="columns" label="Items" />',
  },
  {
    name: "FzList",
    props: "items, label, motionDisabled, duration",
    state: "parent owns mutations",
    slots: "default({item,index}), empty",
    example: "",
  },
  {
    name: "FzAlert",
    props: "title, tone",
    state: "status; danger uses alert",
    slots: "default",
    example: "",
  },
  {
    name: "FzBadge",
    props: "tone",
    state: "presentational",
    slots: "default",
    example: "",
  },
  {
    name: "FzMeter",
    props: "value, max, label, tone",
    state: "presentational",
    slots: "none",
    example: "",
  },
  {
    name: "FzStat",
    props: "value, label, detail",
    state: "presentational",
    slots: "none",
    example: "",
  },
  {
    name: "FzPanel",
    props: "title, eyebrow",
    state: "presentational",
    slots: "default, action, footer",
    example: "",
  },
  {
    name: "FzIcon",
    props: "name, size, strokeWidth, label",
    state: "decorative unless labeled",
    slots: "none",
    example: "",
  },
] as const;
